#                           |------------------------------------------------------------|
#                           |        Plugin created by WHiTeG0Dz_ and for support        |
#                           | Contact me on telegram @GodzHard or Discord WHiTeG0Dz_#2791|
#                           |------------------------------------------------------------|

#The CompassName is used to choose the name of the compass
CompassName: "§bServers §7[Right-Click]"

#The title would be the initial part of the UI
Title: "§r§6Server §eList"

#The description is the part below the UI
Description: "§6Want to §eplay our server?\n§bIt's simple §3just tap a server minigame §byou like."

#The button for teleport in games
Button: "true"
Button-On: "§aOnline §bFactions§3SkyBlock"
Button-Command: "transferserver galaxype.nbb.one 22091"

Button1: "true"
Button1-On: "§cOffline §eSky§6Wars"
Button1-Command: "say In work"

Button2: "true"
Button2-On: "§cOffline §2Anarchy"
Button2-Command: "say work"

Button3: "true"
Button3-On: "§cOffline §5Prison"
Button3-Command: "say work"

Button4: "true"
Button4-On: "§cOffline §cKit§4PvP"
Button4-Command: "say work"

Button5: "false"
Button5-On: "BedWars"
Button5-Command: "mv tp BedWars"

Button6: "false"
Button6-On: "Factions"
Button6-Command: "mv tp Factions"

#For my others plugin visit my profile on GitHub! https://github.com/GodzHardYT
